### PR TITLE
Add Import/Export OPML Activity

### LINKED ISSUE #87: Choose OPML location
Right now, you need to have a file in a certain location, it would be easier for the users to select the file themselves.
This would need a FileSystem popup or ask Android for it.

### PR DESCRIPTION
**Pull request by AugerC**
Changes:
 - Added an activity to import-export opml files.
  - - - - I know i'm bad at doing layouts, this is provisional.
  - - - - There is a problem with the mimetype of the file you select in case you don't have an external file manager
  - - - - The back button on the toolbar of the activity does not work, i'm trying to fix it

  - The dialog the app had before is no longer shown so probably can get deleted. In the future i will.
  - The same goes to some methods of OPMLimportExport.

Resolves #87

Remains to do:
 - Layout:
 - - Fix the back button
 - - Improve, it's ugly

- Delete unnecessary dialogs/activities/classes that are no longer necessary

### CODE REVIEW

**Comment by bottiger** [comment]
Hi! Nice work. However, I do have some changes which needs to be addressed before I can merge it in. The list may be long, but don't feel discouraged.

I can do the changes if you want, but I would advise you to do it :)

### Code style and guidelines:
* Remove all the changes which are not essential from the commit. There are a lot of changes in the AndroidManifest.xml file, and as far as I can see only the addition of the  "OPML_import_export_activity" is relevant.
* MY_PERMISSIONS_REQUEST_READ_CONTACTS is probably not a very good name for requesting permission to the file system :) (SubscriptionFragment.java)
* Could you extract all strings like "RETURN_EXPORT" to some static final variables?
* Strings which are never displayed to the user, like in Log.d(....) should be marked with // NoI18N at the end of the line.
* When you define a method like this `public String getRealPathFromURI(Uri contentUri)` you should annotate the input and output with either @NonNull or @Nullable . Like this:  `@Nullable public String getRealPathFromURI(@NonNull Uri contentUri)` . This allows me (and other) to know what is expected of the method in the future, and prevents a lot of bugs.
* Is the DialogOPML.java even used anymore? If not, get rid of it.
* The "OPML import export activity" should be placed in the package"org.bottiger.podcast.activities.opml_import_export" or something like that.

### Layout
* I was about to make a comment about the statusbar having the wrong color, but I can see this is a general problem in all extra activities - like the DownloadManager and the SettingsActivity.
* You should have a margin on the Layout matching the material guidelines. (https://material.google.com/layout/metrics-keylines.html#metrics-keylines-keylines-spacing) I think it's 16dp, but I may be wrong.
* As you writ eyourself, the "back button" in the ToolBar doesn't work. See DownloadManagerActivity for details on how to make it work.
* If I press "Import OPML" and then the "back button" I finish the ImportExportActivity. I think I should just go back to the activity.

**Comment by bottiger** [comment]
@AugerC  btw, be sure to pull the latest version. I just pushed a bunch of changes - including a fix for the statusbar color

**Comment by AugerC** [comment]
Updated! 
- The changes on the manifest are removed, there are something left, i think is relative to the TAB spacing or something like that.
- MY_PERMISSIONS_REQUEST_READ_CONTACTS no longer exists, this was not supposed to be named like that :S
- The strings like the "RETURN_EXPORT" are now static variables.
- Added the  // NoI18N and @Nullable/@NotNull
- I got rid of the dialog, some changes to other activities were needed to run the project.
- Moved the activity. I thought a package for just this one can be excessive so i put it in .../activities/openopml/but can be modified if you prefer
- The Layout is now working correctly as expected, pressing "Import OPML" and then the "back button" doesn't finish the activity and the upper back button works fine. 
- Now the activity follows the Material Design guidelines (i hope :) )


I think that's all. 
PD: Don't worry about commenting the changes, i want to do things the right way ^^ feel free to coment anything you don't feel confortable about.

**Comment by bottiger** [comment]
@AugerC Looks good. The design definitely looks much cleaner. However, there are still a few small issues.

### Text

- It doesn't really make sense that the first headline says "import or export", and the second one say "export only". I guess the first one should only say "import you subscriptions"
- There is a visible "\n\t" in the export description.

### Importing

- I tried to import a file, and I was just redirected back to the SubscriptionFragment. There is already a class called "OpenOpmlFromIntentActivity". This activity should (and I haven't touched it in ages) show the content of a OPML file, and allow the user to select which podcasts he wants to import. I think the Import Button should start this activity when the user picks a file.

Otherwise I think it's great! Thanks a lot for you work

**Comment by AugerC** [comment]
Hi @bottiger 
I don't know what do you mean with the import line, in my project appears as "unused import" and does nothing. 
I tested the app in my 2 phones and worked great, if you want a logcat i can provide it to you

**Comment by bottiger** [comment]
@AugerC Looks good, but one more thing.  You can not just replace

```
            Uri uri = getIntent().getData();
            File opmlFile = new File(uri.getPath());
```

With 

`File opmlFile = new File(getIntent().getStringExtra(OPML_SUBS_LIST_EXTRA_CODE));`

In the OpenOpmlFromIntentActivity.java. The getIntent().getData() is still just if you manually open a OPML file with SoundWaves from a file editor. I guess you need to test if the intent comes from some other app or your OPML activity.

Otherwise I think I'm ready to pull it into the master branch

**Comment by AugerC** [comment]
Check it out, i think i got what you asked for. 
- Optimized imports
- Commented more unused functions/methods
- Improved the import/export feature:
- - Used to get the result checking if the data returned from
OPML_import_export_activity was a path or not. Now it checks the result
code.
- - OPML_import_export_activity now returns an uri
- - Now OpenOpmlFromIntent is called correctly, working inside the app
and selecting the file from the file manager
- - The result in case of EXPORT is null, i don't know if this may get
some errors or not (it shouldn't)

**Comment by bottiger** [comment]
@AugerC This is some great work, thank you very much! I have merged it into the master branch now.

**Comment by bottiger** [comment]
@AugerC Now that it's merged in. Are you interested in continue to help out with the app? If so there are (obviously) lots of things to do :)

**Comment by AugerC** [comment]
@bottiger Yes, i would like to continue to help out, i liked what i've seen and used so far. 
Although i did this collaboration as a college project (using the hours i plan to dedicate to college) and i'm kinda busy so maybe the collaborations get spaced in time.
I will continue to work in my free time, as i say, i liked the app and a podcatcher is something i use everyday ^^ So yeah, you can expect more work from me.

**Comment by bottiger** [comment]
@AugerC Cool, now you at least know the basics :) As you might know there are plenty of bugs to fix, but there are also some major new features which needs to be engineered. Just ask if you need inspiration.

**Pull request merged**
