### PR TITLE
Added Portuguese language

### PR DESCRIPTION
**Pull request by smarquespt**

### CODE REVIEW

**Comment by bottiger** [comment]
Thank you very much for this. I am looking into it an expect to have it as a part of version 0.74

**Comment by smarquespt** [comment]
@bottiger 

Please add this to 0.74 release.

**Comment by bottiger** [comment]
@smarquespt Thanks again. I have merged it now because you asked. However I am working on a proper contributor license agreement which should help me keep all the legal things in order. When I find one I like I may require you to sign it :)

**Comment by smarquespt** [comment]
@bottiger 

I´m also working on Libreoffice and we use LGPLv3+ and MPL. Maybe it fits you to?

**Pull request merged**
